backend:
  name: git-gateway
  branch: staging # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "src/assets/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Portfolio"
    name: "portfolio"
    files:
      - label: "Github Projects"
        name: "github"
        file: "_collections/github.json"
        fields:
          - label: Projects
            name: projects
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: "Site URL", name: siteUrl, widget: string}
              - {label: "Repo URL", name: repoUrl, widget: string}
              - {label: Description, name: description, widget: text}