backend:
  name: git-gateway
  branch: staging # Branch to update (optional; defaults to master)
  #TODO: Change branch to master when pushing live

# This line should *not* be indented
media_folder: "src/assets/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "assets/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Events"
    name: "events"
    folder: "/public/_collections/events"
    extension: "json"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
  - label: "Portfolio"
    name: "portfolio"
    editor:
      preview: false
    files:
      - label: "Github Projects"
        name: "github"
        file: "/public/_collections/github.json"
        fields:
          - label: Projects
            name: projects
            widget: list
            fields: #TODO: Add select field to choose technologies used
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image} #TODO: Add Default Image
              - {label: "Site URL", name: siteUrl, widget: string}
              - {label: "Repo URL", name: repoUrl, widget: string}
              - {label: Description, name: description, widget: text}